#!/usr/bin/env python3
"""
TOWER5 - script 10: ground truth + tau recomputation at 100 digits.
Recomputes (does not trust the 60-digit file):
  - the five roots of x^5+20x+16 (GROUND TRUTH for the whole build)
  - j_pm = 10400 -/+ 4640 sqrt5  (from Z_B pm = (271 pm 145 sqrt5)/1013888, j = 1728 - 1/Z)
  - tau(pm) by lambda-sextic + K/K' inversion (same procedure as agm_ribbon/03, re-run at dps=100)
  - round-trip 1728*kleinj(tau) vs j
  - Brioschi roots B_Z(x) = x^5 - 10 Z x^3 + 45 Z^2 x - Z^2 for both branches
  - Kiepert map push-through re-verification (lam=-4, mu = (95008-129777664 Z)/145)
Everything printed BEFORE any comparison lines (compute-then-grade).
Saves values to tower5_values.py (importable python literals).
"""
import mpmath as mp
mp.mp.dps = 100

s5 = mp.sqrt(5)
I = mp.mpc(0, 1)

# --- ground truth: roots of x^5+20x+16 ---
qroots = mp.polyroots([1, 0, 0, 0, 20, 16], maxsteps=400, extraprec=400)
print("== ground truth: roots of x^5+20x+16 (dps=100) ==")
for r in qroots:
    print("  ", mp.nstr(r, 50))

# --- branch data (exact, from the certified Kiepert reduction 01/01b) ---
branches = {}
for sgn, name in [(+1, "+"), (-1, "-")]:
    Z = (mp.mpf(271) + sgn*145*s5)/mp.mpf(1013888)
    j = 1728 - 1/Z
    mu = (95008 - 129777664*Z)/145
    lam = mp.mpf(-4)
    branches[name] = dict(Z=Z, j=j, mu=mu, lam=lam)
    print(f"\n== branch ({name}) ==")
    print("  Z_B =", mp.nstr(Z, 50))
    print("  j   =", mp.nstr(j, 50), "  (exact: 10400", "-" if sgn>0 else "+", "4640*sqrt5)")
    # check exact form
    jex = 10400 - sgn*4640*s5
    print("  |j - (10400 -/+ 4640 sqrt5)| =", mp.nstr(abs(j - jex), 5))

# --- lambda sextic inversion, as in 03 but at dps=100 ---
def lambda_roots(j):
    def pmul(a, b):
        c = [mp.mpf(0)]*(len(a)+len(b)-1)
        for i, ai in enumerate(a):
            for k, bk in enumerate(b):
                c[i+k] += ai*bk
        return c
    p1 = [mp.mpf(1), mp.mpf(-1), mp.mpf(1)]
    p3 = pmul(pmul(p1, p1), p1)
    p3 = [256*c for c in p3]
    q1 = pmul([mp.mpf(0), mp.mpf(0), mp.mpf(1)], pmul([mp.mpf(1), mp.mpf(-1)], [mp.mpf(1), mp.mpf(-1)]))
    q1 = [j*c for c in q1]
    n = max(len(p3), len(q1))
    poly = [(p3[i] if i < len(p3) else 0) - (q1[i] if i < len(q1) else 0) for i in range(n)]
    return mp.polyroots(list(reversed(poly)), maxsteps=500, extraprec=500)

taus = {}
for name in ("+", "-"):
    j = branches[name]["j"]
    roots = lambda_roots(j)
    # principal lambda selection as in 03: real in (0,1) & < 1/2 preferred, else smallest |lam|
    lam_m = None
    for r in roots:
        if abs(mp.im(r)) < mp.mpf(10)**(-70) and 0 < mp.re(r) < 1 and mp.re(r) < 0.5:
            lam_m = mp.re(r)
    if lam_m is None:
        lam_m = sorted(roots, key=lambda r: abs(r))[0]
    K = mp.ellipk(lam_m)
    Kp = mp.ellipk(1-lam_m)
    tau = I*Kp/K
    if mp.im(tau) < 0:
        tau = -tau
    rt = abs(1728*mp.kleinj(tau) - j)
    taus[name] = tau
    print(f"\n== branch ({name}) inversion ==")
    print("  lambda =", mp.nstr(lam_m, 50))
    print("  tau    =", mp.nstr(tau, 60))
    print("  |tau|  =", mp.nstr(abs(tau), 50))
    print("  round-trip |1728*kleinj(tau) - j| =", mp.nstr(rt, 5))

# compare with the 60-digit archive values
arch_p = mp.mpc('-0.426097093884528808775669755008358966818122987997461564983268689',
                '0.904677437865651119516162633252530797608512631900460734600314029')
arch_m = mp.mpc('0.0', '1.57635974347832799114392435220924054458524378638948884897859629')
print("\n== agreement with archive tau_values.txt (60-digit) ==")
print("  |tau(+) - archive| =", mp.nstr(abs(taus["+"] - arch_p), 5))
print("  |tau(-) - archive| =", mp.nstr(abs(taus["-"] - arch_m), 5))

# --- Brioschi roots per branch + Kiepert push-through ---
print("\n== Brioschi roots and Kiepert map re-verification ==")
bri = {}
for name in ("+", "-"):
    Z = branches[name]["Z"]; mu = branches[name]["mu"]; lam = branches[name]["lam"]
    co = [1, 0, -10*Z, 0, 45*Z**2, -Z**2]
    br = mp.polyroots(co, maxsteps=400, extraprec=400)
    bri[name] = br
    print(f"-- branch ({name}) Brioschi roots x_k of x^5-10Zx^3+45Z^2x-Z^2:")
    for x in br:
        print("    ", mp.nstr(x, 40))
    ys = [(lam + mu*x)/(x**2/Z - 3) for x in br]
    resid = [min(abs(y - yr) for yr in qroots) for y in ys]
    print("   Kiepert-mapped y_k vs ground truth, max |diff| =", mp.nstr(max(resid), 5))

# --- save ---
with open("/home/claude/tower5/tower5_values.py", "w") as f:
    f.write("# generated by 10_setup_tau.py at dps=100\n")
    f.write("tau_p = %r\n" % taus["+"])
    f.write("tau_m = %r\n" % taus["-"])
    f.write("qroots = %r\n" % (qroots,))
    f.write("bri_p = %r\n" % (bri["+"],))
    f.write("bri_m = %r\n" % (bri["-"],))
print("\n[saved tower5_values.py]")
