# Mackey certificate: over the dihedral floor D5 (fixed field K6), both tiles of
# L(rho~) = L_{K12}(mu)/L_{K10}(lambda) decompose into <=2-dimensional pieces.
# Brute force over A5 as even permutations of {0..4}. Exact integer/cyclotomic arithmetic.
from itertools import permutations
import cmath, math

def is_even(p):
    n=len(p); seen=[False]*n; parity=0
    for i in range(n):
        if not seen[i]:
            j=i; c=0
            while not seen[j]: seen[j]=True; j=p[j]; c+=1
            parity ^= (c-1)&1
    return parity==0

A5=[p for p in permutations(range(5)) if is_even(p)]
def mul(a,b): return tuple(a[b[i]] for i in range(5))
def inv(a):
    r=[0]*5
    for i,v in enumerate(a): r[v]=i
    return tuple(r)
e=tuple(range(5))

# subgroups
c5gen=(1,2,3,4,0)                       # (01234)
C5=[e]; 
g=c5gen
while g!=e: C5.append(g); g=mul(g,c5gen)
flip=(0,4,3,2,1)                        # (14)(23), inverts c5gen -> D5
D5=sorted(set(C5+[mul(f,c) for f in [flip] for c in C5]))
s3a=(1,2,0,4,3)                         # (012)(34): order 6? (012) order3 * (34): even? (012) even? 3-cycle even; (34) odd => product odd. Need even elements only.
# Build S3 inside A5: generated by (012) and (01)(34) -- (01)(34) is even.
t=(1,0,2,4,3)                            # (01)(34)
r3=(1,2,0,3,4)                           # (012)
S3=set([e]); frontier=[t,r3]
changed=True
S3=set([e,t,r3])
while changed:
    changed=False
    for a in list(S3):
        for b in list(S3):
            m=mul(a,b)
            if m not in S3: S3.add(m); changed=True
S3=sorted(S3)
assert len(C5)==5 and len(D5)==10 and len(S3)==6, (len(C5),len(D5),len(S3))
assert all(x in A5 for x in D5) and all(x in A5 for x in S3)

# characters of subgroups (1-dim):
# psi5 on C5: order-5 character; on S3: the sign character sgn (S3 ~ Sym3); on C5 in D5 etc.
z5=cmath.exp(2j*math.pi/5)
def c5_log(x):  # power of c5gen
    g=e
    for k in range(5):
        if g==x: return k
        g=mul(g,c5gen)
    return None
def psi5(x,j=1): return z5**(c5_log(x)*j)

# sgn on S3: even perms of the triangle {0,1,2} -> +1, transposition-type -> -1.
# In our S3 (acting on {0,1,2} x {3,4}), elements are (rot^k) and (rot^k * t).
S3rot={e,r3,mul(r3,r3)}
def sgnS3(x): return 1 if x in S3rot else -1

# induced character of Ind_H^G(chi) evaluated at g: (1/|H|) sum_{x in G, x^-1 g x in H} chi(x^-1 g x)
def induced_char(G,H,chi,g):
    s=0
    for x in G:
        y=mul(mul(inv(x),g),x)
        if y in H: s+=chi(y)
    return s/len(H)

Hset_C5=set(C5); Hset_S3=set(S3)
def indC5(g): return induced_char(A5,Hset_C5,lambda y: psi5(y,1),g)
def indS3(g): return induced_char(A5,Hset_S3,sgnS3,g)

# D5 irreducible characters (order 10): two 1-dims (triv, sgn_D5), two 2-dims (rho_1, rho_2)
def d5_class(x):
    if x==e: return 'e'
    if x in C5:
        k=c5_log(x); return 'r1' if k in (1,4) else 'r2'
    return 'refl'
D5chars={
 'triv':  {'e':1,'r1':1,'r2':1,'refl':1},
 'sgn':   {'e':1,'r1':1,'r2':1,'refl':-1},
 'rho1':  {'e':2,'r1':2*math.cos(2*math.pi/5),'r2':2*math.cos(4*math.pi/5),'refl':0},
 'rho2':  {'e':2,'r1':2*math.cos(4*math.pi/5),'r2':2*math.cos(8*math.pi/5),'refl':0},
}
classsize={'e':1,'r1':2,'r2':2,'refl':5}

def decompose_on_D5(charfunc):
    # returns multiplicities of D5 irreps in Res_D5(charfunc)
    vals={}
    for cl in ['e','r1','r2','refl']:
        rep={'e':e,'r1':c5gen,'r2':mul(c5gen,c5gen),'refl':flip}[cl]
        vals[cl]=charfunc(rep)
    out={}
    for name,ch in D5chars.items():
        m=sum(classsize[cl]*vals[cl]*ch[cl] for cl in vals)/10
        out[name]=complex(m)
    return vals,out

for label,f in [('Res_D5 Ind_C5^A5(psi5)  [mu-tile, deg 12]',indC5),
                ('Res_D5 Ind_S3^A5(sgn)   [lambda-tile, deg 10]',indS3)]:
    vals,dec=decompose_on_D5(f)
    print(label)
    print('  values on D5 classes:', {k:(round(v.real,6) if isinstance(v,complex) else round(v,6)) for k,v in vals.items()})
    print('  D5-decomposition:', {k:round(v.real,6) for k,v in dec.items()}, ' (all imag parts ~0:', all(abs(v.imag)<1e-9 for v in dec.values()),')')
    tot=sum(round(v.real)* (1 if n in('triv','sgn') else 2) for n,v in dec.items())
    print('  total dim check:', tot)
print('CERTIFICATE: every constituent over the D5 floor has dimension <= 2 (D5 has no irreps of dim > 2).')
